### ISSUE TITLE
Release version 0.1

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/bdg-convert#6]

**Comment by heuermh** [comment]
@fnothaft @akmorrow13 @jpdna I'd like to cut a version 0.1 release so that https://github.com/heuermh/biojava-adam and https://github.com/heuermh/biojava-legacy-adam have something to depend on.

I'm ok if this version doesn't yet meet the requirements for refactoring the converter package in ADAM.

**Comment by fnothaft** [comment]
+1, sgtm!

**Comment by heuermh** [comment]
Fixed by commit 483a62a812404852adada39cf6c506dca6843100
